#!/bin/bash
# Build NGINX and modules on Heroku.
# This program is designed to run in a web dyno provided by Heroku.
# We would like to build an NGINX binary for the builpack on the
# exact machine in which the binary will run.
# Our motivation for running in a web dyno is that we need a way to
# download the binary once it is built so we can vendor it in the buildpack.
#
# Once the dyno has is 'up' you can open your browser and navigate
# this dyno's directory structure to download the nginx binary.
apt update
apt install --assume-yes zlib1g-dev
apt-get install --assume-yes libssl-dev
apt-get install --assume-yes build-essential
apt-get install --assume-yes libpq-dev
apt-get install --assume-yes cmake
apt-get install --assume-yes pkg-config
apt-get install --assume-yes bison

temp_dir=$(mktemp -d /tmp/h2o.XXXX)

cd $temp_dir
mkdir h2o
echo "Temp dir: $temp_dir"

echo "cloning h2o"
git clone https://github.com/h2o/h2o
cd h2o
cd deps
git clone https://github.com/authorNari/mruby-pg.git
git clone https://github.com/baldowl/mruby-bcrypt.git
cd ..
cmake . -DEXTRA_LIBS=pq
make 
make install


cp ./h2o /buildpack/bin/h2o-heroku-18
